
package com.emailvision.apiccmd.service.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CcmdServiceService", targetNamespace = "http://api.service.apiccmd.emailvision.com/", wsdlLocation = "http://p5apic.emv2.com/apiccmd/services/CcmdService?wsdl")
public class CcmdServiceService
    extends Service
{

    private final static URL CCMDSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.emailvision.apiccmd.service.api.CcmdServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.emailvision.apiccmd.service.api.CcmdServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://p5apic.emv2.com/apiccmd/services/CcmdService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://p5apic.emv2.com/apiccmd/services/CcmdService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CCMDSERVICESERVICE_WSDL_LOCATION = url;
    }

    public CcmdServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcmdServiceService() {
        super(CCMDSERVICESERVICE_WSDL_LOCATION, new QName("http://api.service.apiccmd.emailvision.com/", "CcmdServiceService"));
    }

    /**
     * 
     * @return
     *     returns CcmdService
     */
    @WebEndpoint(name = "CcmdServicePort")
    public CcmdService getCcmdServicePort() {
        return super.getPort(new QName("http://api.service.apiccmd.emailvision.com/", "CcmdServicePort"), CcmdService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CcmdService
     */
    @WebEndpoint(name = "CcmdServicePort")
    public CcmdService getCcmdServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.service.apiccmd.emailvision.com/", "CcmdServicePort"), CcmdService.class, features);
    }

}
