
package com.emailvision.apiccmd.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "CcmdServiceException", targetNamespace = "http://exceptions.service.apiccmd.emailvision.com/")
public class CcmdServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CcmdExceptionDetails faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CcmdServiceException(String message, CcmdExceptionDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CcmdServiceException(String message, CcmdExceptionDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emailvision.apiccmd.service.api.CcmdExceptionDetails
     */
    public CcmdExceptionDetails getFaultInfo() {
        return faultInfo;
    }

}
