
package com.emailvision.apimember.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ConnectionServiceException", targetNamespace = "http://exceptions.service.apiconnection.emailvision.com/")
public class ConnectionServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConnectionExceptionDetails faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ConnectionServiceException(String message, ConnectionExceptionDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ConnectionServiceException(String message, ConnectionExceptionDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emailvision.apimember.service.api.ConnectionExceptionDetails
     */
    public ConnectionExceptionDetails getFaultInfo() {
        return faultInfo;
    }

}
