
package com.emailvision.apimember.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "MemberServiceException", targetNamespace = "http://exceptions.service.apimember.emailvision.com/")
public class MemberServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MemberExceptionDetails faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public MemberServiceException(String message, MemberExceptionDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public MemberServiceException(String message, MemberExceptionDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emailvision.apimember.service.api.MemberExceptionDetails
     */
    public MemberExceptionDetails getFaultInfo() {
        return faultInfo;
    }

}
