
package com.emailvision.apibatchmember.service.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "BatchMemberServiceException", targetNamespace = "http://exceptions.service.apibatchmember.emailvision.com/")
public class BatchMemberServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BatchMemberExceptionDetails faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BatchMemberServiceException(String message, BatchMemberExceptionDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BatchMemberServiceException(String message, BatchMemberExceptionDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emailvision.apibatchmember.service.api.BatchMemberExceptionDetails
     */
    public BatchMemberExceptionDetails getFaultInfo() {
        return faultInfo;
    }

}
