
package com.emailvision.apibatchmember.service.api;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BatchMemberService", targetNamespace = "http://api.service.apibatchmember.emailvision.com/")
@XmlSeeAlso({
    com.emailvision.apibatchmember.service.api.ObjectFactory.class,
    com.emailvision.apibatchmember.service.exceptions.ObjectFactory.class,
    com.emailvision.apiconnection.service.exceptions.ObjectFactory.class
})
public interface BatchMemberService {


    /**
     * 
     * @param token
     * @param file
     * @param insertUpload
     * @return
     *     returns long
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFileInsert", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.UploadFileInsert")
    @ResponseWrapper(localName = "uploadFileInsertResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.UploadFileInsertResponse")
    public long uploadFileInsert(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "insertUpload", targetNamespace = "")
        InsertUpload insertUpload,
        @WebParam(name = "file", targetNamespace = "")
        DataHandler file)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

    /**
     * 
     * @param uploadId
     * @param token
     * @return
     *     returns java.lang.String
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBadFile", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetBadFile")
    @ResponseWrapper(localName = "getBadFileResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetBadFileResponse")
    public String getBadFile(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "uploadId", targetNamespace = "")
        long uploadId)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

    /**
     * 
     * @param token
     * @param file
     * @param mergeUpload
     * @return
     *     returns long
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFileMerge", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.UploadFileMerge")
    @ResponseWrapper(localName = "uploadFileMergeResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.UploadFileMergeResponse")
    public long uploadFileMerge(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "mergeUpload", targetNamespace = "")
        MergeUpload mergeUpload,
        @WebParam(name = "file", targetNamespace = "")
        DataHandler file)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

    /**
     * 
     * @param uploadId
     * @param token
     * @return
     *     returns java.lang.String
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLogFile", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetLogFile")
    @ResponseWrapper(localName = "getLogFileResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetLogFileResponse")
    public String getLogFile(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "uploadId", targetNamespace = "")
        long uploadId)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

    /**
     * 
     * @param pwd
     * @param login
     * @param key
     * @return
     *     returns java.lang.String
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openApiConnection", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.OpenApiConnection")
    @ResponseWrapper(localName = "openApiConnectionResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.OpenApiConnectionResponse")
    public String openApiConnection(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd,
        @WebParam(name = "key", targetNamespace = "")
        String key)
        throws ConnectionServiceException
    ;

    /**
     * 
     * @param token
     * @return
     *     returns java.lang.String
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "closeApiConnection", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.CloseApiConnection")
    @ResponseWrapper(localName = "closeApiConnectionResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.CloseApiConnectionResponse")
    public String closeApiConnection(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws ConnectionServiceException
    ;

    /**
     * 
     * @param pwd
     * @param partnerkey
     * @param login
     * @return
     *     returns com.emailvision.apibatchmember.service.api.ApiPartnerConnectionResult
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openPartnerConnection", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.OpenPartnerConnection")
    @ResponseWrapper(localName = "openPartnerConnectionResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.OpenPartnerConnectionResponse")
    public ApiPartnerConnectionResult openPartnerConnection(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "pwd", targetNamespace = "")
        String pwd,
        @WebParam(name = "partnerkey", targetNamespace = "")
        String partnerkey)
        throws ConnectionServiceException
    ;

    /**
     * 
     * @param token
     * @return
     *     returns java.util.List<com.emailvision.apibatchmember.service.api.UploadInfo>
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpload", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetLastUpload")
    @ResponseWrapper(localName = "getLastUploadResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetLastUploadResponse")
    public List<UploadInfo> getLastUpload(
        @WebParam(name = "token", targetNamespace = "")
        String token)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

    /**
     * 
     * @param uploadId
     * @param token
     * @return
     *     returns com.emailvision.apibatchmember.service.api.UploadStatus
     * @throws BatchMemberServiceException
     * @throws ConnectionServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUploadStatus", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetUploadStatus")
    @ResponseWrapper(localName = "getUploadStatusResponse", targetNamespace = "http://api.service.apibatchmember.emailvision.com/", className = "com.emailvision.apibatchmember.service.api.GetUploadStatusResponse")
    public UploadStatus getUploadStatus(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "uploadId", targetNamespace = "")
        long uploadId)
        throws BatchMemberServiceException, ConnectionServiceException
    ;

}
